permalink: /:title/

title : Tom Joynt
tagline: Awesome Things
author :
  name : Tom Joynt
  email : tpjoynt@gmail.com
  github : tpjoynt
  twitter : tpjoynt

# Used to not clutter the root directory with pages.
collections:
 - sections

production_url : http://tpjoynt.github.com