permalink: /:title/

title : Tom Joynt
tagline: Awesome Things
author :
  name : Tom Joynt
  email : tpjoynt@gmail.com
  github : tpjoynt
  twitter : tpjoynt

include: ['_sections']

defaults:
  -
    values:
      layout: "default"

production_url : http://tpjoynt.github.com